FROM docker.io/library/postgres:15.3-bookworm

ARG DEBIAN_FRONTEND=noninteractive
ENV LANG=C

RUN \
	apt update; \
	apt upgrade -y; \
	apt install --no-install-recommends -y \
	cron

COPY . /static

ENTRYPOINT ["/static/scripts/postgres/init.sh"]
