services:
  postgres:
    container_name: postgres
    build: containers/postgres
    volumes:
      - ./containers/postgres/volume:/app
      - ./containers/postgres/volume/data/postgres:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=debian
     - POSTGRES_PASSWORD=secret
    networks:
      - postgres
    ports:
      - 5432:5432

  adminer:
    container_name: adminer 
    image: adminer:4.8.1-standalone
    networks:
      - postgres 
    ports:
      - 8081:8080

networks:
  postgres:
    name: postgres 
    external: true
